### PR TITLE
Remove the current top card with custom animations.

### PR DESCRIPTION
**Pull request by dlazaro66**
This adds two public methods to your library that extends the API. 
`removeTopCardWithOffScreenTopAnimation()`
and
`removeTopCardWithCustomAnimation(Animation animation) `

I also removed `RemoveViewOnAnimCompleted extends AsyncTask` since is not really useful if we  have the `AnimatorListener`class that do this stuff by us.

### CODE REVIEW

**Comment by dlazaro66** [comment]
Really good library man, We're surprised about this! We needed this feature so this is the pull request we implemented, please check this out and merge if you consider it's ok :smile:

**Comment by dlazaro66** [comment]
Hi! I detected minor issues in my changes and I'm still working to solve it, please don't merge it yet

**Comment by aaronbond** [comment]
ok let me know how it goes.

**Comment by dlazaro66** [comment]
Finally I'm going to close this Pull Request, I made some improvements removing the idle `AsyncTask` for example and replacing it with AnimationListeners, but I think that the change has introduced some side effects to the current library behavior, so merging it will cause library to fail in some cases I think.

Since I spent a few hours with this I would recommend you a few improvements to the code, for example if you're using a specific code style add it to the readme file. 
I would add the methods I tried to implement since It will extend the library posibilites 
`removeTopCardWithOffScreenTopAnimation()`
`removeTopCardWithCustomAnimation(Animation animation)`
`getTopView()` -> This one is working well, you can add it in your next development iteration 
`getCurrentPositionInAdapter()` -> This one is working well, you can add it in your next development iteration
There are a few hacky lines of code that could be refactored/improved sometimes is hard to know exactly what the library is suponed to do (this for example: https://github.com/aaronbond/Swipe-Deck/blob/master/cardstack/src/main/java/com/daprlabs/cardstack/SwipeDeck.java#L337)

Anyway this is my feedback after a few changes, Your library is pretty cool and have a lot of potential, good job man! thanks.

**Pull request closed without merging**
